version: "3.8"
services:
  pharmacy-redis:
    container_name: pharmacy-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: yessm621/pharmacy-redis
    ports:
      - "6379:6379"
  pharmacy-database:
    container_name: pharmacy-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: yessm621/pharmacy-database
    environment:
      - MARIADB_DATABASE=pharmacy
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./databases/config:/etc/mysql/conf.d
    ports:
      - "3306:3306"
